query CoachUserDetail($userId: String!) {
  coachUserDetail(userId: $userId) {
    displayName
    email
    height
    currentWeight
    goal
    pathologies
    imc
    evolutionData {
      week
      weight
      calories
      score
    }
    todayMeals {
      id
      name
      consumedAt
      calories
      protein
      carbs
      fat
      aiScore
      photo
      aiInsights
      coachComment
      coachName
    }
  }
}
