query CoachDashboardData {
  coachDashboardData {
    stats {
      users {
        count
        evolution
      }
      publishedRecipes {
        count
        evolution
      }
      scannedMeals {
        count
        evolution
      }
      averageScore {
        count
        evolution
      }
    }
    recentUsers {
      name
      email
      score
      currentWeight
      goal
      targetDailyCalories
    }
    recentRecipes {
      id
      name
      photo
      calories
      proteins
      carbs
      lipids
    }
  }
}
