name: "integration-test"

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/test-integration.yml"
      - ".github/workflows/test-backend.yml"
  workflow_dispatch:
  workflow_call:

jobs:
  test-server:
    uses: ./.github/workflows/test-backend.yml
